name: CI/CD Lambda

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main
      - '*'

jobs:
  lint-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          pip install -r lambda-template/requirements.txt
      - name: Run lint test
        run: |
          pylint lambda-template/ --rcfile=lambda-template/.pylintrc
  unit-test:
    runs-on: self-hosted
    needs: ['lint-test']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'